apiVersion: v1
kind: ConfigMap
metadata:
  name: kk-payments-config
  namespace: kijani-staging

data:
  NODE_ENV: "staging"
  DB_HOST: "postgres-staging"
  DB_PORT: "5432"
  LOG_LEVEL: "warn"
  APP_PORT: "3001"
  MAX_CONNECTIONS: "10"
